import Link from "next/link";
import { contentPath, contentStatusLabel, contentTypeLabel } from "@/lib/content";
import prisma from "@/lib/prisma";
export const dynamic = "force-dynamic";
export default async function ContentsPage() {
  const posts = await prisma.contentPost.findMany({ include: { district: { select: { name: true } } }, orderBy: [{ updatedAt: "desc" }] });
  return <div><div className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-2xl font-bold text-neutral-950">İçerikler</h1><p className="mt-1 text-sm text-neutral-500">Blog ve rehber içeriklerini tek yerden yönet.</p></div><Link href="/panel/icerikler/yeni" className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-bold text-white">Yeni içerik</Link></div>
  <div className="mt-6 overflow-hidden rounded-2xl border border-black/[0.06] bg-white">{posts.length ? <div className="divide-y divide-neutral-100">{posts.map(post => <div key={post.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-fuchsia-50 px-2 py-1 text-[10px] font-bold uppercase text-fuchsia-700">{contentTypeLabel(post.type)}</span><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px] font-bold uppercase text-neutral-600">{contentStatusLabel(post.status)}</span>{post.district ? <span className="text-xs text-neutral-500">{post.district.name}</span> : null}</div><h2 className="mt-2 truncate font-bold text-neutral-950">{post.title}</h2><p className="mt-1 text-xs text-neutral-500">/{post.type === "GUIDE" ? "rehber" : "blog"}/{post.slug}</p></div><div className="flex shrink-0 gap-2"><Link target="_blank" href={contentPath(post.type, post.slug)} className="rounded-lg border border-neutral-200 px-3 py-2 text-xs font-semibold text-neutral-600">Görüntüle</Link><Link href={`/panel/icerikler/${post.id}`} className="rounded-lg bg-neutral-950 px-3 py-2 text-xs font-semibold text-white">Düzenle</Link></div></div>)}</div> : <p className="p-10 text-center text-sm text-neutral-500">Henüz içerik eklenmedi.</p>}</div></div>;
}
