import { PlacementType, UserRole } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth";
import prisma from "@/lib/prisma";
import PlacementForm from "./PlacementForm";
import { deletePlacementAction, togglePlacementAction } from "./actions";

const labels:Record<PlacementType,string>={HOME_HERO:"Ana sayfa hero",HOME_FEATURED:"Ana sayfa öne çıkan",LISTINGS_FEATURED:"İlanlar sayfası",DISTRICT_TOP:"İlçe üst alanı",CATEGORY_TOP:"Kategori üst alanı",DISTRICT_CATEGORY_TOP:"İlçe + kategori"};
const date=(d:Date)=>new Intl.DateTimeFormat("tr-TR",{dateStyle:"medium"}).format(d);
export default async function PlacementsPage(){await requireRole([UserRole.ADMIN]);const now=new Date();const[placements,products,districts,categories]=await Promise.all([prisma.placement.findMany({orderBy:[{isActive:"desc"},{expiresAt:"asc"}],include:{product:{select:{name:true}},district:{select:{name:true}},category:{select:{name:true}}}}),prisma.product.findMany({where:{isActive:true},orderBy:{name:"asc"},select:{id:true,name:true}}),prisma.district.findMany({where:{isActive:true},orderBy:{name:"asc"},select:{id:true,name:true}}),prisma.listingCategory.findMany({where:{isActive:true},orderBy:{name:"asc"},select:{id:true,name:true}})]);return <div className="space-y-6"><div><p className="text-sm text-neutral-500">VIP ve Premium görünürlük yönetimi</p><h1 className="text-3xl font-semibold tracking-tight">Reklam Konumları</h1></div><PlacementForm products={products} districts={districts} categories={categories}/><div className="overflow-hidden rounded-2xl border border-black/[0.06] bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500"><tr><th className="px-4 py-3">İlan</th><th className="px-4 py-3">Konum</th><th className="px-4 py-3">Kapsam</th><th className="px-4 py-3">Sıra</th><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3">İşlem</th></tr></thead><tbody>{placements.map(item=>{const expired=item.expiresAt<=now;const active=item.isActive&&!expired;return <tr key={item.id} className="border-t border-neutral-100"><td className="px-4 py-4 font-medium">{item.product.name}</td><td className="px-4 py-4">{labels[item.type]}</td><td className="px-4 py-4 text-neutral-600">{[item.district?.name,item.category?.name].filter(Boolean).join(" / ")||"Genel"}</td><td className="px-4 py-4">{item.position}</td><td className="px-4 py-4 text-xs text-neutral-600">{date(item.startsAt)} — {date(item.expiresAt)}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${active?"bg-emerald-50 text-emerald-700":expired?"bg-red-50 text-red-700":"bg-neutral-100 text-neutral-600"}`}>{active?"Aktif":expired?"Süresi bitti":"Pasif"}</span></td><td className="px-4 py-4"><div className="flex gap-2"><form action={togglePlacementAction.bind(null,item.id)}><button className="rounded-lg border px-3 py-1.5 text-xs">{item.isActive?"Durdur":"Aktifleştir"}</button></form><form action={deletePlacementAction.bind(null,item.id)}><button className="rounded-lg border border-red-200 px-3 py-1.5 text-xs text-red-600">Sil</button></form></div></td></tr>})}{placements.length===0&&<tr><td colSpan={7} className="px-4 py-10 text-center text-neutral-500">Henüz reklam konumu yok.</td></tr>}</tbody></table></div></div></div>}
