"use client";
import { useActionState } from "react";
import { createPlacementAction, type PlacementFormState } from "./actions";

type Option={id:string;name:string};
const initial:PlacementFormState={};
const input="mt-2 w-full rounded-xl border border-neutral-200 bg-white px-3 py-2 text-sm outline-none focus:border-neutral-950";
function localDate(offsetDays:number){const d=new Date();d.setDate(d.getDate()+offsetDays);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
export default function PlacementForm({products,districts,categories}:{products:Option[];districts:Option[];categories:Option[]}){const[state,action,pending]=useActionState(createPlacementAction,initial);return <form action={action} className="space-y-4 rounded-2xl border border-black/[0.06] bg-white p-5"><div><h2 className="text-lg font-semibold">Yeni reklam konumu</h2><p className="mt-1 text-sm text-neutral-500">Aynı konum ve sırada tarih çakışmasına izin verilmez.</p></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">İlan<select name="productId" className={input} required><option value="">Seçiniz</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-medium">Konum türü<select name="type" className={input} defaultValue="HOME_FEATURED"><option value="HOME_HERO">Ana sayfa hero</option><option value="HOME_FEATURED">Ana sayfa öne çıkan</option><option value="LISTINGS_FEATURED">İlanlar sayfası öne çıkan</option><option value="DISTRICT_TOP">İlçe üst alanı</option><option value="CATEGORY_TOP">Kategori üst alanı</option><option value="DISTRICT_CATEGORY_TOP">İlçe + kategori üst alanı</option></select></label></div><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">İlçe<select name="districtId" className={input}><option value="">Genel</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-medium">Kategori<select name="categoryId" className={input}><option value="">Genel</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-medium">Sıra<input name="position" type="number" min="1" defaultValue="1" className={input}/></label></div><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium">Başlangıç<input name="startsAt" type="datetime-local" defaultValue={localDate(0)} className={input} required/></label><label className="text-sm font-medium">Bitiş<input name="expiresAt" type="datetime-local" defaultValue={localDate(30)} className={input} required/></label></div><label className="text-sm font-medium">Not<input name="note" className={input} placeholder="Müşteri, ödeme veya kampanya notu"/></label>{state.error&&<p className="text-sm text-red-600">{state.error}</p>}{state.success&&<p className="text-sm text-emerald-600">{state.success}</p>}<button disabled={pending} className="rounded-xl bg-neutral-950 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{pending?"Kaydediliyor...":"Konum oluştur"}</button></form>}
