"use server";
import { revalidatePath } from "next/cache";
import { Prisma, UserRole } from "@/generated/prisma/client";
import { requireRole } from "@/lib/auth";
import { writeAuditLog } from "@/lib/audit";
import prisma from "@/lib/prisma";
export type CategoryFormState = { error?: string; success?: string };
const text = (fd: FormData, key: string) => typeof fd.get(key) === "string" ? String(fd.get(key)).trim() : "";
const slugify = (v: string) => v.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g,"i").replace(/ğ/g,"g").replace(/ü/g,"u").replace(/ş/g,"s").replace(/ö/g,"o").replace(/ç/g,"c").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");
function data(fd: FormData) { const name=text(fd,"name"), slug=slugify(text(fd,"slug")||name); if(name.length<2) throw new Error("Kategori adı en az 2 karakter olmalı."); if(!slug) throw new Error("Geçerli slug oluşturulamadı."); const sortOrder=Number(text(fd,"sortOrder")||0); return { name, slug, shortDescription:text(fd,"shortDescription")||null, description:text(fd,"description")||null, seoTitle:text(fd,"seoTitle")||null, seoDescription:text(fd,"seoDescription")||null, sortOrder:Number.isFinite(sortOrder)?sortOrder:0, isActive:fd.get("isActive")==="on" }; }
export async function createCategoryAction(_: CategoryFormState, fd: FormData): Promise<CategoryFormState> { const actor=await requireRole([UserRole.ADMIN]); try { const item=await prisma.listingCategory.create({data:data(fd)}); await writeAuditLog({actor,action:"CREATE",entityType:"ListingCategory",entityId:item.id,description:`${item.name} kategorisi oluşturuldu.`}); revalidatePath("/panel/kategoriler"); revalidatePath("/kategoriler"); revalidatePath("/sitemap.xml"); return {success:"Kategori oluşturuldu."}; } catch(e){ if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002") return {error:"Bu kategori veya slug zaten var."}; return {error:e instanceof Error?e.message:"Kategori oluşturulamadı."}; } }
export async function updateCategoryAction(id:string,_:CategoryFormState,fd:FormData):Promise<CategoryFormState>{const actor=await requireRole([UserRole.ADMIN]);try{const item=await prisma.listingCategory.update({where:{id},data:data(fd)});await writeAuditLog({actor,action:"UPDATE",entityType:"ListingCategory",entityId:id,description:`${item.name} kategorisi güncellendi.`});revalidatePath("/panel/kategoriler");revalidatePath("/kategoriler");revalidatePath(`/kategori/${item.slug}`);revalidatePath("/sitemap.xml");return{success:"Kategori kaydedildi."};}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==="P2002")return{error:"Bu slug başka kategoride kullanılıyor."};return{error:e instanceof Error?e.message:"Kategori güncellenemedi."};}}
